dataset:
  dataset:
    name: coz_folder
    args:
      root_path: "data/coz_data/train_LR"
      # first_k: 100
  wrapper:
    name: coz_wrapper
    args:
      'cell_decode': True
  test_ratio: 0.01
  batch_size: 1

model:
  name: liif
  args:
    encoder_spec:
        name: edsr_baseline
        args:
            no_upsampling: True,
    imnet_spec:
        name: mlp
        args:
          out_dim: 3
          hidden_list: [256, 256, 256, 256]
    focal_spec:
        name: focal_mlp
        args:
          in_dim: 256

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100